apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    namespace: {{.Values.namespace}}
    labels:
        app: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: persistentvolumeclaim
            containers:
                - name: postgres
                  image: postgres:14.6-bullseye
                  ports:
                      - containerPort: 5432
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: db-username
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: db-secret
                                key: db-password
                      - name: POSTGRES_DB
                        value: {{.Values.postgres.db}}
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: {{.Values.namespace}}
spec:
    selector:
        app: postgres
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
