apiVersion: apps/v1
kind: Deployment
metadata:
    name: web1-deployment
    namespace: {{.Values.namespace}}
    labels:
        app: web1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: web1
    template:
        metadata:
            labels:
                app: web1
        spec:
            containers:
                - name: web1
                  image: yeasy/simple-web
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: web1-service
    namespace: {{.Values.namespace}}
spec:
    selector:
        app: web1
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
